# Generated by Django 5.2 on 2025-04-07 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=400)),
                ('state', models.CharField(choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Kano', 'Kano'), ('Rivers', 'Rivers')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('min_experience_years', models.PositiveIntegerField()),
                ('job_field', models.CharField(choices=[(1, 'Marketing'), (2, 'Information Technology'), (3, 'Finance'), (4, 'Accounting'), (5, 'Design'), (6, 'Healthcare'), (7, 'Engineering')], max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('responsibility', models.TextField()),
                ('qualification', models.TextField()),
                ('perks', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
