# Generated by Django 5.2 on 2025-04-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_field',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Information Technology', 'Information Technology'), ('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Design', 'Design'), ('Healthcare', 'Healthcare'), ('Engineering', 'Engineering')], max_length=100),
        ),
    ]
