# Generated by Django 5.2 on 2025-04-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_job_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_disabled',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20),
        ),
    ]
